name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Xvfb and dependencies
        run: |
          sudo apt-get update
          # Устанавливаем Xvfb и все необходимые X11-утилиты (включая xdpyinfo)
          sudo apt-get install -y xvfb xauth x11-utils x11-apps libxkbcommon-x11-0
          # Запускаем виртуальный дисплей
          Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV
          # Проверяем что Xvfb работает (теперь xdpyinfo будет доступен)
          xdpyinfo -display $DISPLAY
          echo "Xvfb is running on $DISPLAY"

      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager
          # Дополнительные зависимости для GUI
          pip install pyautogui PyVirtualDisplay

      - name: Run tests
        run: |
          python -m pytest -v
