name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Xvfb and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xauth x11-utils libxkbcommon-x11-0
          
          # Запускаем Xvfb в фоновом режиме с ожиданием
          Xvfb :99 -screen 0 1280x1024x24 &
          sleep 5  # Даем время на запуск
          
          # Проверяем что процесс запущен
          ps aux | grep Xvfb
          
          # Устанавливаем переменную DISPLAY
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV
          
          # Проверяем доступность дисплея (теперь xdpyinfo установлен)
          xdpyinfo -display $DISPLAY || echo "Xvfb check failed, but continuing"

      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager PyVirtualDisplay

      - name: Run tests
        run: |
          python -m pytest -v
