name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Xvfb with auth
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xauth libgt

      - name: Copy source code
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v4  # Рекомендуется v4 (v5 не существует)
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get install -y chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest webdriver-manager  # Добавляем обязательные пакеты

      - name: Run tests
        run: |
          export DISPLAY=:99
          python -m pytest -v
