name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Xvfb with proper auth
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xauth
          
          # Создаем и настраиваем .Xauthority
          touch ~/.Xauthority
          xauth generate :99 . trusted
          
          # Запускаем Xvfb с ожиданием
          Xvfb :99 -screen 0 1280x1024x24 &
          sleep 3
          
          # Проверяем процесс
          ps aux | grep Xvfb
          
          # Устанавливаем переменные окружения
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV
          echo "XAUTHORITY=$HOME/.Xauthority" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager pyautogui PyVirtualDisplay

      - name: Run tests
        run: |
          # Дополнительная проверка окружения
          echo "Current DISPLAY: $DISPLAY"
          echo "XAUTHORITY: $XAUTHORITY"
          ls -la ~/.Xauthority
          
          python -m pytest -v
